/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ontap;

import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.Format;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author dontwait
 */
public class GuiTinhTienDien extends javax.swing.JFrame {

    /**
     * Creates new form GuiTinhTienDien
     */
    public GuiTinhTienDien() {
        initComponents();
        customInitPlaceholders();
        
        /*
        Những điều lưu ý khi làm bài kiểm tra 
        1. Để test mặc định để dễ bắt lỗi - Dùng Focuslost để bắt sự kiện null cho 
        dễ
        2. Viết hàm check parse(String, trả true nếu parse được, đưa vào focuslost để bắt lỗi
        3. Hàm StringFormat để tạo hiển thị in đẹp mắt 
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSoDienCu = new javax.swing.JTextField();
        lblSoDienCu = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        lblSoDienMoi = new javax.swing.JLabel();
        txtSoDienMoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKetQua = new javax.swing.JTextField();
        btnQuit = new javax.swing.JButton();
        btnTinh = new javax.swing.JButton();
        lblSoDienCu1 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        lblHeader.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblHeader.setText("CHƯƠNG TRÌNH TÍNH TIỀN ĐIỆN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        txtSoDienCu.setFont(new java.awt.Font("sansserif", 2, 22)); // NOI18N
        txtSoDienCu.setForeground(new java.awt.Color(153, 153, 153));
        txtSoDienCu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoDienCuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoDienCuFocusLost(evt);
            }
        });
        txtSoDienCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienCuActionPerformed(evt);
            }
        });

        lblSoDienCu.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        lblSoDienCu.setText("Số điện cũ:");

        lblDonGia.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        lblDonGia.setText("Đơn giá điện/Kwh:");

        txtDonGia.setFont(new java.awt.Font("sansserif", 2, 22)); // NOI18N
        txtDonGia.setForeground(new java.awt.Color(153, 153, 153));
        txtDonGia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDonGiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDonGiaFocusLost(evt);
            }
        });
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        lblSoDienMoi.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        lblSoDienMoi.setText("Số điện mới:");

        txtSoDienMoi.setFont(new java.awt.Font("sansserif", 2, 22)); // NOI18N
        txtSoDienMoi.setForeground(new java.awt.Color(153, 153, 153));
        txtSoDienMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoDienMoiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoDienMoiFocusLost(evt);
            }
        });
        txtSoDienMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienMoiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        jLabel5.setText("Kết quả");

        txtKetQua.setEditable(false);
        txtKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetQuaActionPerformed(evt);
            }
        });

        btnQuit.setText("Thoát");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });

        lblSoDienCu1.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        lblSoDienCu1.setText("Mã khách hàng:");

        txtMaKhachHang.setFont(new java.awt.Font("sansserif", 2, 22)); // NOI18N
        txtMaKhachHang.setForeground(new java.awt.Color(153, 153, 153));
        txtMaKhachHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaKhachHangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaKhachHangFocusLost(evt);
            }
        });
        txtMaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKhachHangActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoDienMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienMoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKetQua)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoDienCu1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKhachHang)
                            .addComponent(txtSoDienCu))))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSoDienCu1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtSoDienCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienCuActionPerformed
        txtSoDienCu.setText("");
        
    }//GEN-LAST:event_txtSoDienCuActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void txtSoDienMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienMoiActionPerformed
        txtSoDienMoi.setText("");
    }//GEN-LAST:event_txtSoDienMoiActionPerformed

    private void txtKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetQuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetQuaActionPerformed
    private void customInitPlaceholders() {
        
        txtMaKhachHang.setForeground(Color.red);
        
        txtSoDienCu.setText("input old so dien");
        txtSoDienCu.setForeground(Color.RED);

        txtSoDienMoi.setText("input new so dien");
        txtSoDienMoi.setForeground(Color.RED);
        
        txtDonGia.setText("example: 5000");
        txtDonGia.setForeground(Color.red);
    }
    private void txtSoDienCuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienCuFocusGained
        if (txtSoDienCu.getText().equals("input old so dien")) {
            txtSoDienCu.setText("");
            txtSoDienCu.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtSoDienCuFocusGained

    private void txtSoDienMoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienMoiFocusGained
        if(txtSoDienMoi.getText().equals("input new so dien")) {
            txtSoDienMoi.setText("");
            txtSoDienMoi.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtSoDienMoiFocusGained

    private void txtSoDienCuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienCuFocusLost
        if(txtSoDienCu.getText().equals("")) {
            txtSoDienCu.setText("input old so dien");
            txtSoDienCu.setForeground(Color.yellow);
        }
    }//GEN-LAST:event_txtSoDienCuFocusLost

    private void txtSoDienMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoDienMoiFocusLost
        if(txtSoDienMoi.getText().equals("")) {
            txtSoDienMoi.setText("input new so dien");
            txtSoDienMoi.setForeground(Color.yellow);
        }
    }//GEN-LAST:event_txtSoDienMoiFocusLost

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Xác nhận thoát", "Do you want to quit", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void txtMaKhachHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKhachHangFocusGained
        if(txtMaKhachHang.getText().equals("example: KH001")) {
            txtMaKhachHang.setText("");
            txtMaKhachHang.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtMaKhachHangFocusGained

    private void txtMaKhachHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKhachHangFocusLost
        if(txtMaKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ma khach hang not null or empty");
            txtMaKhachHang.requestFocusInWindow();
        }    
    }//GEN-LAST:event_txtMaKhachHangFocusLost

    private void txtMaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKhachHangActionPerformed
        if(txtMaKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ma khach hang not null or empty");
            txtMaKhachHang.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtMaKhachHangActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        txtMaKhachHang.setText("");
        txtMaKhachHang.requestFocus();
        txtSoDienCu.setText("");
        txtSoDienMoi.setText("");
        txtDonGia.setText("");
        txtKetQua.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed
    private boolean checkParseDouble(String textInput, String textField, Component parent) {
        try {
            Double.parseDouble(textInput);
            return true;
        }catch(NumberFormatException numex) {
            JOptionPane.showMessageDialog(this, textField + " Invalid! Pls Try typing double");
        }
        return false;
    
    }
    private double calculateTotalCost(double soDienCu, double soDienMoi, double donGia) {
        double soDienTieuThu = soDienMoi - soDienCu;
        if(soDienTieuThu < 500)
            return soDienTieuThu * donGia;
        return soDienTieuThu * donGia * 1.2;
    }
    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        String soDienCuStr = txtSoDienCu.getText();
        String soDienMoiStr = txtSoDienMoi.getText();
        String donGiaStr = txtDonGia.getText();
        
        
        boolean isSoDienCuValid = checkParseDouble(soDienCuStr, "So dien cu", this);
        boolean isSoDienMoiValid = checkParseDouble(soDienMoiStr, "So dien moi", this);
        boolean isDonGiaValid = checkParseDouble(donGiaStr, "Don gia", this);
        
        if(!isSoDienCuValid) {
            txtSoDienCu.requestFocus();
            txtSoDienCu.setText("");
            return;
        }
        if(!isSoDienMoiValid) {
            txtSoDienMoi.requestFocus();
            txtSoDienMoi.setText("");
            return;
        }
        if(!isDonGiaValid) {
            txtDonGia.requestFocus();
            txtDonGia.setText("");
            return;
        }
        
        Double soDienCu = Double.parseDouble(soDienCuStr);
        Double soDienMoi = Double.parseDouble(soDienMoiStr);
        Double donGia = Double.parseDouble(donGiaStr);
        
        if(soDienCu > soDienMoi) {
            JOptionPane.showMessageDialog(this, "So dien moi phai lon hon so dien cu!");
            txtSoDienMoi.setText("");
            txtSoDienMoi.requestFocus();
            return;
        }
            
        
        double soDienTieuThu = soDienMoi - soDienCu;
        DecimalFormat formatter = new DecimalFormat("#, ###");
        String result = formatter.format(calculateTotalCost(soDienCu, soDienMoi, donGia)) + " VND";
        txtKetQua.setText(result);
    }//GEN-LAST:event_btnTinhActionPerformed

    private void txtDonGiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonGiaFocusGained
        if(txtDonGia.getText().equals("example: 5000")) {
           txtDonGia.setText("");
           txtDonGia.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtDonGiaFocusGained

    private void txtDonGiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDonGiaFocusLost
        if(txtDonGia.getText().equals("")) {
           txtDonGia.setText("example: 5000");
           txtDonGia.setForeground(Color.yellow);
        }
    }//GEN-LAST:event_txtDonGiaFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTinhTienDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTinhTienDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblSoDienCu;
    private javax.swing.JLabel lblSoDienCu1;
    private javax.swing.JLabel lblSoDienMoi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoDienCu;
    private javax.swing.JTextField txtSoDienMoi;
    // End of variables declaration//GEN-END:variables
}
